CREATE TABLE IF NOT EXISTS backend.location_group
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_location_group
            PRIMARY KEY NOT NULL UNIQUE,
    uuid UUID NOT NULL UNIQUE,
    group_name VARCHAR(255) NOT NULL
);

ALTER TABLE backend.location_group OWNER TO postgres;

CREATE TABLE IF NOT EXISTS backend.location
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_location
            PRIMARY KEY NOT NULL UNIQUE,
    uuid UUID NOT NULL UNIQUE ,
    location_name VARCHAR(255),
    location_group_id INTEGER
        CONSTRAINT fk_location_location_group
            REFERENCES backend.location_group
);
ALTER TABLE backend.location OWNER TO postgres;


CREATE TABLE IF NOT EXISTS backend.device
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_device
            PRIMARY KEY NOT NULL UNIQUE,
    uuid UUID NOT NULL UNIQUE,
    device_id VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(255) NOT NULL,
    location_id INTEGER NOT NULL
        CONSTRAINT fk_device_location
            REFERENCES backend.location,
    created_at TIMESTAMP DEFAULT now() NOT NULL,
    updated_at TIMESTAMP DEFAULT NULL
);

ALTER TABLE backend.device OWNER TO postgres;

CREATE INDEX ix_device_device_id
    ON backend.device (device_id);

CREATE TABLE IF NOT EXISTS backend.temp_history
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_temp_history
            PRIMARY KEY NOT NULL UNIQUE,
    uuid UUID NOT NULL UNIQUE,
    temp INTEGER NOT NULL,
    device_id INTEGER
        CONSTRAINT fk_temp_history_device
            REFERENCES backend.device,
    get_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE backend.temp_history OWNER TO postgres;

CREATE TABLE IF NOT EXISTS backend.users
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_users
            PRIMARY KEY NOT NULL UNIQUE,
    uuid UUID NOT NULL UNIQUE,
    login VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    created_at TIMESTAMP DEFAULT now() NOT NULL,
    updated_at TIMESTAMP DEFAULT NULL
    --ADD location_group owner, location_group user access
);

ALTER TABLE backend.users OWNER TO postgres;
