version: '3.4'
services:
  websockify:
    image: efrecon/websockify
    ports:
      - "8090:8090"
    command: [ '8090', '192.168.2.125:5900' ]

  zookeeper:
    image: adamoss/rpi-zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: charlesyan/rpi-kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "ScanNotificationTopic:1:1,TransferRequestDoneTopic:1:1,PickRequestDoneTopic:1:1,TransferRequestTopic:1:1,PickRequestBundleTopic:1:1,ActionTopic:1:1,PlcInformationRequestTopic:1:1,PlcInformationResponseTopic:1:1,"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock